### PR TITLE
Migrate to mdbook

### PR DESCRIPTION
**Pull request by NamsooCho**

### CODE REVIEW

**Comment by kpp** [comment]
> src/static/path.png

Why did you convert all images to png?

**Comment by NamsooCho** [comment]
github pages do not allow to render `svg` format in markdown for security issues.

https://github.com/nbedos/termtosvg/issues/61#issuecomment-413332388

**Comment by kpp** [comment]
However .svg is a source code for .png, we'd better keep .svg but render it into png to have a possibility to change images

**Comment by NamsooCho** [comment]
Rendering is allowed, if svg reside in github. I missed something before.

**Review by kpp — APPROVED** [review]

**Comment by kpp** [comment]
@suhr should we keep .msc files too?

**Comment by suhr** [comment]
Yes, it would be nice to keep all the sources.

**Review by suhr — APPROVED** [review]
:shipit:

**Pull request merged**
